一模一样#yi@mu@yi@yang
一模二样#yi@mu@er@yang
乔模乔样#qiao@mu@qiao@yang
乔模样#qiao@mu@yang
人模人样#ren@mu@ren@yang
人模狗样#ren@mu@gou@yang
人模狗样儿#ren@mu@gou@yang@er
像模像样#xiang@mu@xiang@yang
像模象样#xiang@mu@xiang@yang
冲模#chong@mu
大模厮样#da@mu@si@yang
大模大样#da@mu@da@yang
大模尸样#da@mu@shi@yang
字模#zi@mu
寿头模子#shou@tou@mu@zi
恶模样#e@mu@yang
时装模特儿#shi@zhuang@mu@te@er
模具#mu@ju
模子#mu@zi
模板#mu@ban
模样#mu@yang
红模子#hong@mu@zi
脸模子#lian@mu@zi
装模作样#zhuang@mu@zuo@yang
铜模#tong@mu
锭模#ding@mu
锻模#duan@mu
