为什么#wei@shen@me
什么#shen@me
什么事#shen@me@shi
什么人#shen@me@ren
什么意思#shen@me@yi@si
什么时候#shen@me@shi@hou
什么样#shen@me@yang
什么的#shen@me@de
到什么山上唱什么歌#dao@shen@me@shan@shang@chang@shen@me@ge
干什么#gan@shen@me
没什么#mei@shen@me
