一曝十寒#yi@pu@shi@han
偃曝#yan@pu
寝关曝纩#qin@guan@pu@kuang
晒曝#shai@pu
曝书#pu@shu
曝书亭词#pu@shu@ting@ci
曝书见竹#pu@shu@jian@zhu
曝场#pu@chang
曝射#pu@she
曝尸#pu@shi
曝巫#pu@wu
曝扬#pu@yang
曝昳#pu@yi
曝晒#pu@shai
曝献#pu@xian
曝皮#pu@pi
曝背#pu@bei
曝背食芹#pu@bei@shi@qin
曝腮#pu@sai
曝腮之鱼#pu@sai@zhi@yv
曝腮龙门#pu@sai@long@men
曝芹#pu@qin
曝衣#pu@yi
曝衣楼#pu@yi@lou
曝裈#pu@kun
曝阳#pu@yang
曝露#pu@lu
曝骨履肠#pu@gu@lv@chang
曝鳃#pu@sai
炽曝#chi@pu
献曝#xian@pu
献曝之忱#xian@pu@zhi@chen
田父献曝#tian@fu@xian@pu
盐曝#yan@pu
芹曝#qin@pu
表曝#biao@pu
负曝#fu@pu
贫儿曝富#pin@er@pu@fu
野人奏曝#ye@ren@zou@pu
野人献曝#ye@ren@xian@pu
