俭朴#jian@pu
朴厚#pu@hou
朴学#pu@xue
朴实#pu@shi
朴实头#pu@shi@tou
朴实无华#pu@shi@wu@hua
朴拙#pu@zhuo
朴直#pu@zhi
朴素#pu@su
朴素唯物主义#pu@su@wei@wu@zhu@yi
朴素无华#pu@su@wu@hua
朴素的唯物主义#pu@su@de@wei@wu@zhu@yi
朴茂#pu@mao
朴讷#pu@ne
朴讷诚笃#pu@ne@cheng@du
朴质#pu@zhi
朴陋#pu@lou
素朴实在论#su@pu@shi@zai@lun
艰苦朴素#jian@ku@pu@su
