伊瓜苏瀑布#yi@gua@su@pu@bu
卡兰博瀑布#ka@lan@bo@pu@bu
壶口瀑布#hu@kou@pu@bu
安赫尔瀑布#an@he@er@pu@bu
尼亚加拉瀑布#ni@ya@jia@la@pu@bu
望庐山瀑布#wang@lu@shan@pu@bu
瀑布#pu@bu
瀑水#pu@shui
莫西奥图尼亚瀑布#mo@xi@ao@tu@ni@ya@pu@bu
飞瀑#fei@pu
黄果树瀑布#huang@guo@shu@pu@bu
